[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/contract"
  to = "/contract.html"
  status = 200
